logging:
  level:
    com.foalnet: trace

server:
  port: 8080
  session-timeout: 30
  tomcat:
    uri-encoding: UTF-8

spring:
  http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true
  datasource:
      driverClassName: com.mysql.jdbc.Driver #{com.microsoft.sqlserver.jdbc.SQLServerDriver \ com.mysql.jdbc.Driver}
      url: jdbc:mysql://localhost:3306/cloud-sale?useUnicode=true&characterEncoding=UTF-8 #{jdbc:sqlserver://localhost:1433;DatabaseName=cloud-sale \ jdbc:mysql://localhost:3306/cloud-sale}
      username: fyqvip
      password: 911120
      type: com.alibaba.druid.pool.DruidDataSource
      connectionProperties: druid.stat.mergeSql=true

mapper:
    mappers: tk.mybatis.springboot.util.MyMapper
    not-empty: false
    identity: MYSQL #{SQLSERVER \ MYSQL}

pagehelper:
    helperDialect: mysql #{mysql | SQLSERVER}
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql