logging:
  level:
    com.foalnet: trace

server:
  port: 9090
  session-timeout: 30
  tomcat:
    uri-encoding: UTF-8

spring:
  http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true
  datasource:
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://localhost:1433;DatabaseName=cloud-sale
      username: sa
      password: 911120
      type: com.alibaba.druid.pool.DruidDataSource
      connectionProperties: druid.stat.mergeSql=true

mapper:
    mappers: tk.mybatis.springboot.util.MyMapper
    not-empty: false
    identity: SQLSERVER

pagehelper:
    helperDialect: sqlserver
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql